name: Unrelease NPM package

run-name: Unrelease ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Tag
        default: v0.0.0
        required: true

jobs:
  unrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete tag
        run: git push --delete origin ${{ steps.tag.outputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Unpublish from NPM
        run: npm unpublish @apecommerce/ape-common@${{ steps.tag.outputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
