name: Release NPM package

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v0.0.0-dev.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint:ci

      - name: Run tests
        run: yarn test:ci

      - name: Build package
        run: yarn build

      - name: Set package version
        run: sed -i "s|0.0.0|${{ steps.tag.outputs.version }}|" package.json

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |-
          npm publish
            --access=public
            --tag=dev
