name: Release NPM packages

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v0.0.0-dev.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint:ci

      - name: Run unit tests
        run: yarn test:ci test/unit

      - name: Do things
        run: |
          echo $GITHUB_WORKSPACE
          echo pwd
          ls

      # - name: Publish packages to NPM
      #   run: |
      #     yarn build:server
      #     yarn build:common
      #     ./package.sh server
      #     ./package.sh common
      #     sed -i "s|__version__|${{ steps.tag.outputs.version }}|" dist/server/package.json
      #     sed -i "s|__version__|${{ steps.tag.outputs.version }}|" dist/common/package.json
      #     sed -i "s|__description__|${{ github.event.repository.description }}|" dist/server/package.json
      #     sed -i "s|__description__|${{ github.event.repository.description }}|" dist/common/package.json
      #     cd dist/server
      #     npm publish --tag=dev
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
